-- 운영자 통계 함수 — 실제 정의는 Supabase에 apply_migration으로 적용됨(admin_stats_fix).
-- SECURITY DEFINER + auth.jwt() 이메일 화이트리스트('j.yxl0905@gmail.com'). 집계만 반환, 개인 식별 정보 없음.
-- 운영자 추가 시: 함수 안의 `caller_email not in (...)` 목록에 이메일 추가 후 재적용.
-- 호출: supabase.rpc('admin_stats')  (클라이언트 /admin 페이지)
-- 반환 키: totals, signups_by_week, events_by_day, events_by_type_30d, grad_year, major, applicant_status,
--   has_counselor, school_accredited, target_mode, target_tier, gpa_band, sat_status, sat_band, toefl_status,
--   math_course, info_sources, top_schools, activity_self, quiz, clarity, checklist_progress, axis_avg,
--   most_checked, least_checked, app_usage, rounds, reminders_sent
