-- F4 C7 데이터 (Top 20 / 티어1 23곳) — 공식 CDS만, 2026-08-10 검증·승인
-- Brown(13)은 라이브 공식 소스 부재로 null 처리 (docs/c7-report.md 참고)
update schools set c7_very_important = array['rigor','class_rank','gpa','standardized_tests','essay','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://ir.princeton.edu/sites/g/files/toruqf2041/files/documents/CDS_2526_Princeton_v2.pdf' where id = 1;
update schools set c7_very_important = array['character']::text[], c7_source_url = 'https://ir.mit.edu/projects/2025-26-common-data-set/' where id = 2;
update schools set c7_very_important = '{}', c7_source_url = 'https://oira.harvard.edu/files/2026/07/CDS_2025-2026.pdf' where id = 3;
update schools set c7_very_important = array['rigor','class_rank','gpa','standardized_tests','essay','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://irds.stanford.edu/data-findings/cds' where id = 4;
update schools set c7_very_important = array['rigor','class_rank','gpa','essay','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://oir.yale.edu/sites/default/files/yale_cds_2025-26_md_20260616.pdf' where id = 5;
update schools set c7_very_important = array['rigor','essay','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://data.uchicago.edu/files/2025/08/CDS_2024-2025_to_publish.pdf' where id = 6;
update schools set c7_very_important = array['rigor','gpa','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://ir.provost.duke.edu/sites/default/files/CDS_PDF_2025-2026-20260622-website-published-version.pdf' where id = 7;
update schools set c7_very_important = array['rigor','class_rank','gpa','standardized_tests','essay','recommendations']::text[], c7_source_url = 'https://oira.jhu.edu/wp-content/uploads/2025-2026-CDS-Johns-Hopkins-University-v2.pdf' where id = 8;
update schools set c7_very_important = array['rigor','class_rank','gpa','essay','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://enrollment.northwestern.edu/data/2024-2025.pdf' where id = 9;
update schools set c7_very_important = array['rigor','gpa','essay','recommendations','character']::text[], c7_source_url = 'https://upenn.box.com/s/ckv4frz37rzxa4u6bdiv2h4yzykqm4ef' where id = 10;
update schools set c7_very_important = array['rigor','standardized_tests','essay','recommendations','character']::text[], c7_source_url = 'https://iro.caltech.edu/documents/31491/Caltech_CDS_2024-2025_May_2025.pdf' where id = 11;
update schools set c7_very_important = array['rigor','essay','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://irp.cornell.edu/wp-content/uploads/2026/06/CDS-Cornell-2025-2026-v2.xlsx' where id = 12;
update schools set c7_very_important = null, c7_source_url = null where id = 13;
update schools set c7_very_important = array['rigor','class_rank','gpa','standardized_tests','essay','recommendations','extracurricular','character']::text[], c7_source_url = 'https://www.dartmouth.edu/oir/pdfs/cds_2025-26.pdf' where id = 14;
update schools set c7_very_important = array['rigor','class_rank','gpa','essay','recommendations','extracurricular','character']::text[], c7_source_url = 'https://opir.columbia.edu/sites/opir.columbia.edu/files/content/Common%20Data%20Set/2024-25_Columbia_College_and_Columbia_Engineering_CDS.pdf' where id = 15;
update schools set c7_very_important = array['rigor','gpa','essay']::text[], c7_source_url = 'https://docs.google.com/spreadsheets/d/1INsGFH6MhaO-MFMBZ1Dngcn84FeN-hc0BLS0-v8TL_k/edit' where id = 16;
update schools set c7_very_important = array['rigor','class_rank','gpa','standardized_tests','essay','recommendations','extracurricular','talent','character']::text[], c7_source_url = 'https://ideas.rice.edu/wp-content/uploads/2026/07/CDS_2025-26_WEBSITE.pdf' where id = 17;
update schools set c7_very_important = array['rigor','gpa','essay']::text[], c7_source_url = 'https://apb.ucla.edu/file/f8f5c864-93be-4b44-b646-7807a685749f' where id = 18;
update schools set c7_very_important = array['rigor','class_rank','gpa','essay','extracurricular','character']::text[], c7_source_url = 'https://cdn.vanderbilt.edu/vu-wpfsx/wp-content/uploads/sites/70/2026/07/CDS_2025-2026.xlsx' where id = 19;
update schools set c7_very_important = array['rigor','class_rank','gpa','extracurricular','character','volunteer_work']::text[], c7_source_url = 'https://www.cmu.edu/ira/CDS/pdf/cds_2025_26/cds-2025-c-first-time-first-year-admission.pdf' where id = 20;
update schools set c7_very_important = array['rigor','gpa']::text[], c7_source_url = 'https://obp.umich.edu/wp-content/uploads/pubdata/cds/cds_2025-26_umaa.pdf' where id = 21;
update schools set c7_very_important = array['rigor','class_rank','gpa','essay','recommendations','extracurricular','talent','character','volunteer_work']::text[], c7_source_url = 'https://drive.google.com/drive/folders/1TsZYMnJhOYuNfNYsaziNrbm9uJIqLS_u' where id = 22;
update schools set c7_very_important = array['rigor','class_rank','gpa','standardized_tests','essay','recommendations','talent','character']::text[], c7_source_url = 'https://washu.edu/app/uploads/2026/06/2025-2026-WashU-CDS.pdf' where id = 23;
