-- 심리학 전공 체크리스트 7개 (2026-08-20 승인 후 적용됨, id 145-151, KO+EN)
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order, is_guide, title_en, why_how_en) values
(145, '관심 질문 정하기 (수면·SNS·집중력 등)', '심리학 스파이크는 ''사람에 관심''이 아니라 구체적 질문에서 시작', 9, 'fall', 'psychology', null, false, false, 'spike', 350, false, 'Pick a question you care about (sleep, social media, focus, etc.)', 'A psychology spike starts with a concrete question, not just ''being interested in people'''),
(146, '첫 미니 설문 연구 완주 — 수집→분석→짧은 보고서', '작아도 완주한 연구 1개가 독서 100권보다 강함', 10, 'fall', 'psychology', null, false, false, 'spike', 360, false, 'Finish your first mini survey study — collect → analyze → short report', 'One completed study, however small, beats a hundred books read'),
(147, '11학년 AP Psychology + Statistics 신청 확정', '심리학=통계 학문임을 아는 지원자의 신호', 10, 'spring', 'psychology', null, false, false, 'rigor', 370, false, 'Lock in AP Psychology + Statistics for 11th grade', 'Signals you know psychology runs on statistics'),
(148, '멘탈헬스 캠페인·또래 교육 활동 시작', '상담 흉내(윤리 문제) 대신 교육·캠페인으로 — 리더십 축', 10, 'summer', 'psychology', null, false, false, 'leadership', 380, false, 'Start a mental-health campaign or peer education activity', 'Education and campaigns, not imitation counseling (an ethics problem) — this builds the leadership axis'),
(149, '연구 규모 키우기 — 표본 확대·설계 개선', '원서에 들어갈 마지막 수확기 시작', 11, 'fall', 'psychology', null, false, false, 'spike', 390, false, 'Scale up the research — bigger sample, better design', 'The last harvest season that goes on your application begins'),
(150, '학생 저널(JEI 등) 투고 또는 과학전람회 행동과학 부문 출품', '비용 거의 없이 결과물이 남는 외부 검증', 11, 'spring', 'psychology', null, false, false, 'validation', 400, false, 'Submit to a student journal (e.g., JEI) or enter a science fair behavioral science category', 'External validation that leaves an output at almost no cost'),
(151, '연구·캠페인 결과 정리 — 표본 수·발행 횟수 원서 반영', '숫자로 남긴 기록이 활동란 재료', 11, 'summer', 'psychology', null, false, false, 'story', 410, false, 'Wrap up research and campaign results — put sample sizes and issue counts on the application', 'Records kept in numbers become the material for your activities section');
