-- 시드 데이터 (src/data/*.seed.json에서 자동 생성 — 직접 수정하지 말 것)
-- schema.sql 실행 후 Supabase SQL Editor에서 실행

delete from checklist_items;
delete from schools;

insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (1, 'Princeton University', '프린스턴 대학교', 1, 1, 1510, 1570, 'PLACEHOLDER', null, true, false, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (2, 'MIT', '매사추세츠 공과대학교', 2, 1, 1520, 1580, 'PLACEHOLDER', null, true, false, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (3, 'Harvard University', '하버드 대학교', 3, 1, 1500, 1580, 'PLACEHOLDER', null, true, false, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (4, 'Stanford University', '스탠퍼드 대학교', 4, 1, 1500, 1570, 'PLACEHOLDER', null, false, false, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (5, 'Yale University', '예일 대학교', 5, 1, 1500, 1560, 'PLACEHOLDER', null, true, false, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (6, 'University of Michigan, Ann Arbor', '미시간 대학교 앤아버', 21, 2, 1350, 1530, 'PLACEHOLDER', null, false, false, '{"cs","engineering"}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (7, 'Emory University', '에모리 대학교', 24, 2, 1420, 1540, 'PLACEHOLDER', null, false, true, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (8, 'New York University', '뉴욕 대학교', 30, 2, 1470, 1560, 'PLACEHOLDER', null, false, false, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (9, 'Boston University', '보스턴 대학교', 41, 3, 1360, 1500, 'PLACEHOLDER', null, false, true, '{}', 'PLACEHOLDER', 'PLACEHOLDER');
insert into schools (id, name, name_ko, usnews_rank, tier, sat_mid50_low, sat_mid50_high, gpa_note, intl_accept_rate, need_blind_intl, demonstrated_interest, direct_admit_majors, what_they_value, source_url) values (10, 'University of Wisconsin-Madison', '위스콘신 대학교 매디슨', 39, 3, 1340, 1500, 'PLACEHOLDER', null, false, false, '{"engineering","business"}', 'PLACEHOLDER', 'PLACEHOLDER');

insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (1, 'PLACEHOLDER — 9학년 Fall 공통 항목 1', 'PLACEHOLDER', 9, 'fall', null, null, false, false, 'rigor', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (2, 'PLACEHOLDER — 9학년 Fall 공통 항목 2', 'PLACEHOLDER', 9, 'fall', null, null, false, false, 'spike', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (3, 'PLACEHOLDER — 9학년 Fall 국제학생 항목', 'PLACEHOLDER', 9, 'fall', null, null, true, false, 'story', 30);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (4, 'PLACEHOLDER — 9학년 Spring 공통 항목 1', 'PLACEHOLDER', 9, 'spring', null, null, false, false, 'leadership', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (5, 'PLACEHOLDER — 9학년 Spring 카운슬러 없음 항목', 'PLACEHOLDER', 9, 'spring', null, null, false, true, 'story', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (6, 'PLACEHOLDER — 9학년 Summer 공통 항목 1', 'PLACEHOLDER', 9, 'summer', null, null, false, false, 'spike', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (7, 'PLACEHOLDER — 9학년 Summer 공통 항목 2', 'PLACEHOLDER', 9, 'summer', null, null, false, false, 'validation', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (8, 'PLACEHOLDER — 10학년 Fall 공통 항목 1', 'PLACEHOLDER', 10, 'fall', null, null, false, false, 'rigor', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (9, 'PLACEHOLDER — 10학년 Fall CS 전공 항목', 'PLACEHOLDER', 10, 'fall', 'cs', null, false, false, 'spike', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (10, 'PLACEHOLDER — 10학년 Fall 공통 항목 2', 'PLACEHOLDER', 10, 'fall', null, null, false, false, 'testing', 30);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (11, 'PLACEHOLDER — 10학년 Spring 공통 항목 1', 'PLACEHOLDER', 10, 'spring', null, null, false, false, 'leadership', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (12, 'PLACEHOLDER — 10학년 Spring 국제학생 항목', 'PLACEHOLDER', 10, 'spring', null, null, true, false, 'testing', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (13, 'PLACEHOLDER — 10학년 Summer 공통 항목 1', 'PLACEHOLDER', 10, 'summer', null, null, false, false, 'spike', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (14, 'PLACEHOLDER — 10학년 Summer 공통 항목 2', 'PLACEHOLDER', 10, 'summer', null, null, false, false, 'validation', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (15, 'PLACEHOLDER — 11학년 Fall 공통 항목 1', 'PLACEHOLDER', 11, 'fall', null, null, false, false, 'testing', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (16, 'PLACEHOLDER — 11학년 Fall 공통 항목 2', 'PLACEHOLDER', 11, 'fall', null, null, false, false, 'rigor', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (17, 'PLACEHOLDER — 11학년 Fall 카운슬러 없음 항목', 'PLACEHOLDER', 11, 'fall', null, null, false, true, 'story', 30);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (18, 'PLACEHOLDER — 11학년 Spring 공통 항목 1', 'PLACEHOLDER', 11, 'spring', null, null, false, false, 'testing', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (19, 'PLACEHOLDER — 11학년 Spring Top20 지망 항목', 'PLACEHOLDER', 11, 'spring', null, 1, false, false, 'spike', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (20, 'PLACEHOLDER — 11학년 Spring 공통 항목 2', 'PLACEHOLDER', 11, 'spring', null, null, false, false, 'leadership', 30);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (21, 'PLACEHOLDER — 11학년 Summer 공통 항목 1', 'PLACEHOLDER', 11, 'summer', null, null, false, false, 'story', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (22, 'PLACEHOLDER — 11학년 Summer 공통 항목 2', 'PLACEHOLDER', 11, 'summer', null, null, false, false, 'spike', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (23, 'PLACEHOLDER — 12학년 Fall 공통 항목 1', 'PLACEHOLDER', 12, 'fall', null, null, false, false, 'story', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (24, 'PLACEHOLDER — 12학년 Fall 공통 항목 2', 'PLACEHOLDER', 12, 'fall', null, null, false, false, 'testing', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (25, 'PLACEHOLDER — 12학년 Fall 국제학생 항목', 'PLACEHOLDER', 12, 'fall', null, null, true, false, 'story', 30);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (26, 'PLACEHOLDER — 12학년 Fall 카운슬러 없음 항목', 'PLACEHOLDER', 12, 'fall', null, null, false, true, 'story', 40);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (27, 'PLACEHOLDER — 12학년 Spring 공통 항목 1', 'PLACEHOLDER', 12, 'spring', null, null, false, false, 'story', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (28, 'PLACEHOLDER — 12학년 Spring 국제학생 항목', 'PLACEHOLDER', 12, 'spring', null, null, true, false, 'story', 20);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (29, 'PLACEHOLDER — 12학년 Summer 공통 항목 1', 'PLACEHOLDER', 12, 'summer', null, null, false, false, 'story', 10);
insert into checklist_items (id, title, why_how, grade, season, major_category, tier_condition, intl_only, no_counselor_only, axis, sort_order) values (30, 'PLACEHOLDER — 12학년 Summer 공통 항목 2', 'PLACEHOLDER', 12, 'summer', null, null, false, false, 'validation', 20);
