-- 2026-09-26 미국 학생(시민권·영주권자) 전용 체크리스트 11개 — 사용자 승인 (docs/us-checklist-draft.md)
alter table public.checklist_items add column if not exists us_only boolean not null default false;
insert into public.checklist_items (id,title,why_how,grade,season,major_category,tier_condition,intl_only,no_counselor_only,axis,sort_order,is_guide,title_en,why_how_en,us_only) values
(152,'거주 주 주립대 입학 과목 요건 확인','주립대는 주마다 최소 이수 과목이 정해져 있음(예: UC A-G) — 9학년부터 맞춰 들어야 12학년에 모자라지 않음',9,'fall',null,null,false,false,'rigor',95,true,'Check your state university course requirements','Public universities set minimum courses by state (e.g., UC A-G) — plan from 9th grade so you''re not short in 12th',true),
(153,'Dual enrollment·학교 밖 심화 과목 가능 여부 확인','학교에 없는 심화 과목은 지역 대학 수업(dual enrollment)으로 채울 수 있는지 학교에 확인',10,'fall',null,null,false,false,'rigor',95,true,'See if dual enrollment can fill advanced courses','If your school lacks an advanced course, ask whether a local college course (dual enrollment) can fill it',true),
(154,'PSAT/NMSQT로 National Merit 장학 프로그램 참가','11학년 PSAT/NMSQT가 National Merit 장학 프로그램 진입 시험 — 미국 시민권·영주권자가 대상',11,'fall',null,null,false,false,'testing',95,false,'Take the PSAT/NMSQT for the National Merit program','The 11th-grade PSAT/NMSQT is the entry test for the National Merit Scholarship Program — for U.S. citizens and permanent residents',true),
(155,'목표 학교 Net Price Calculator로 우리 집 실제 부담액 계산','정가가 아니라 보조금 뺀 실제 부담액으로 비교 — 모든 대학이 공식 계산기를 제공 (학교 상세에 링크)',11,'spring',null,null,false,false,'story',95,true,'Run each target school''s Net Price Calculator','Compare what your family would actually pay after grants, not sticker price — every college has an official calculator (linked on each school page)',true),
(156,'거주 주 주립대 자동 합격·보장 제도 확인','텍사스 상위 % 자동 합격, UC ELC(상위 9%)처럼 석차 기준 제도가 있는 주가 있음 — 해당되면 조건을 미리 확인',11,'spring',null,null,false,false,'rigor',95,false,'Check your state''s automatic-admission programs','Some states admit by class rank (e.g., Texas top-percent rules, UC ELC top 9%) — check the conditions early if they apply',true),
(157,'StudentAid.gov 계정(FSA ID) 만들기 — 학생·부모','FAFSA 작성·서명에 학생과 부모 계정이 모두 필요 — 12학년 가을 전에 미리',11,'summer',null,null,false,false,'story',95,false,'Create StudentAid.gov accounts (FSA ID) — student and parent','Both student and parent accounts are needed to complete and sign the FAFSA — set them up before fall of 12th grade',true),
(158,'FAFSA 제출','연방 학자금(Pell Grant·연방 대출·근로장학) 신청서 — 가을에 열리고, 주·학교 마감이 연방 마감보다 이른 경우가 많음',12,'fall',null,null,false,false,'story',95,false,'Submit the FAFSA','The federal aid application (Pell Grants, federal loans, work-study) — it opens in the fall, and state and college deadlines are often earlier than the federal one',true),
(159,'CSS Profile 제출 (요구 학교만)','사립대 상당수가 학교 장학금 심사에 FAFSA와 별도로 요구 — 학교 상세에서 요구 여부 확인',12,'fall',null,null,false,false,'story',95,false,'Submit the CSS Profile (only where required)','Many private colleges require it for their own aid in addition to the FAFSA — check each school page',true),
(160,'주 정부 학자금 신청 조건·마감 확인','주마다 FAFSA 외 추가 서류나 더 이른 마감이 있음 — 거주 주 기준으로 확인',12,'fall',null,null,false,false,'story',95,true,'Check state grant rules and deadlines','States may require extra forms or earlier deadlines than the FAFSA — check your state',true),
(161,'합격 학교별 학자금 제안(financial aid offer) 비교','장학금·보조금(갚지 않는 돈)과 대출을 나눠서, 실제 부담액 기준으로 비교',12,'spring',null,null,false,false,'story',95,true,'Compare financial aid offers','Separate grants and scholarships (free money) from loans, and compare by what you''d actually pay',true),
(162,'주립대 거주자 학비 자격(residency) 확인','주 거주자 학비를 받으려면 학교가 요구하는 거주 확인 서류가 있을 수 있음 — 등록 전 확인',12,'spring',null,null,false,false,'story',95,true,'Confirm in-state residency for tuition','Public universities may require residency documents for in-state tuition — confirm before enrolling',true)
on conflict (id) do nothing;
